version: "3"
services:
  app:
    container_name: "app"
    build: ./app/
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "psqldb"
      DB_PORT: 5432
      DB_USER: "admin"
      DB_PASSWORD: "passwd"
      DB_DEFAULT_DB_NAME: "url_shortener"
    depends_on:
      - postgres
    restart: always
  
  postgres:
    container_name: psqldb
    image: postgres:latest
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "passwd"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always